### ISSUE TITLE
Plutonium files not found on Steam Deck

### ISSUE THREAD

**Issue by ImTheTruth** [JugAndDoubleTap/LanLauncher#2]
![Screenshot_20230524_102250-2](https://github.com/JugAndDoubleTap/LanLauncher/assets/134523239/5514b9e3-c50a-4948-a87c-30262cc9d8a1)
![Screenshot_20230524_102330](https://github.com/JugAndDoubleTap/LanLauncher/assets/134523239/52a6a314-9a05-458f-b8f0-42712036f23b)

**Comment by JugAndDoubleTap** [comment]
it refers to the plutonium folder in appdata, if you installed the prefix from lutris then the correct path should be 

C:/users/deck/appdata/local/plutonium
assuming you ran LanLauncher in the plutonium prefix
