### ISSUE TITLE
BO2 Zombies crashes ten minutes into game.

### ISSUE THREAD

**Issue by calvincorrieri** [JugAndDoubleTap/LanLauncher#5]
About 10 minutes into a zombies game, my game crashes and spits out this error. Crash dump included. Using Lutris on Steam Deck.

Exception Code: 0xC0000005
Exception Address: 0x00000006

https://drive.google.com/file/d/1c3AVlNQzMBVk2nycKuLTk3hYDJ7IwryQ/view?usp=drivesdk

**Comment by calvincorrieri** [comment]
Idk if this is a LanLauncher issue or something else, but I’d appreciate your help.

**Comment by gamebeaker** [comment]
@calvincorrieri do you get the error if you play the game from the plutonium launcher in lan mode (without LanLauncher)?

**Comment by calvincorrieri** [comment]
I’m not sure, since I’m on Steam Deck and they’re all blocked from the Plutonium servers. Hence why I’m using LanLauncher.

**Comment by gamebeaker** [comment]
@calvincorrieri i don't have a Steam Deck maybe you can try the following on it i describe how i did it on Win10.
In the Plutonium folder go in bin right-click "plutonium-bootstrapper-win32.exe" create shortcut.
The new shortcut -> right-click -> properties -> Shortcut
edit Target: `"your-Plutonium-path\Plutonium\bin\plutonium-bootstrapper-win32.exe" t6zm "your-COD2-path\Call of Duty Black Ops II" +name "your-custom-name" -lan`
edit Start in: `"your-Plutonium-path\Plutonium"`
Don't forget to change: your-Plutonium-path, your-COD2-path, your-custom-name

If your game still crashes it isn't a Problem from LanLauncher but from Plutonium on Steam Deck.
Hint: Have you re-verified your COD installations with Steam? Maybe a gamefile is broken.

**Comment by JugAndDoubleTap** [comment]
> About 10 minutes into a zombies game, my game crashes and spits out this error. Crash dump included. Using Lutris on Steam Deck.
> 
> Exception Code: 0xC0000005 Exception Address: 0x00000006
> 
> https://drive.google.com/file/d/1c3AVlNQzMBVk2nycKuLTk3hYDJ7IwryQ/view?usp=drivesdk

most likely a wine/proton issue, try a different version and see if that helps

**Comment by calvincorrieri** [comment]
I verified my files and they’re all intact. I changed a bunch of stuff around in winecfg and the game no longer crashes, but it stutters now instead. After the same amount of time, the frames get super choppy, and what’s really weird is that it only happens when I move the mouse. I used a mod menu to turn on aimbot and the aimbot moving the camera doesn’t affect the fps at all. The fps issues persist even in the main menu, where moving the mouse drops frames too. The frame drops are also weird in that they happen independently from my fps cap. If it’s capped at 60, it’ll drop to 30-40, but if I lock it at 30, it’s still just as choppy. I think it might be a library/driver issue with wine and the mouse input, or it’s some kind of memory leak.

**Comment by JugAndDoubleTap** [comment]
> I verified my files and they’re all intact. I changed a bunch of stuff around in winecfg and the game no longer crashes, but it stutters now instead. After the same amount of time, the frames get super choppy, and what’s really weird is that it only happens when I move the mouse. I used a mod menu to turn on aimbot and the aimbot moving the camera doesn’t affect the fps at all. The fps issues persist even in the main menu, where moving the mouse drops frames too. The frame drops are also weird in that they happen independently from my fps cap. If it’s capped at 60, it’ll drop to 30-40, but if I lock it at 30, it’s still just as choppy. I think it might be a library/driver issue with wine and the mouse input, or it’s some kind of memory leak.
> 
> Is there a “best” version of Plutonium to use for BO2? Idk if an older one might fix it.

i personally use "lutris-7.2.2-x86_64" and play with 0 issues (dxvk enabled)
