### ISSUE TITLE
So,you say it works on Linux....

### ISSUE THREAD

**Issue by Lux-pogu** [JugAndDoubleTap/LanLauncher#7]
Every time I try to use it on steam deck (with proton ge 8-28),it gives the error "The selection in field "Black ops II folder" does not contain valid black ops II game data". the thing is,when I put my sd card into my windows PC,it works perfectly fine - the files aren't the problem. is it because it's on the sd card?

edit: black ops 1 works though?? I had to replace the binkw32.dll file,but it works? I tried the same for bo2 but it's like it doesn't recognize the files for it. maybe I should get a different version from Pluto t6?

**Comment by JugAndDoubleTap** [comment]
Make sure the correct folder is selected, and if it is then you may be missing files for your black ops 2

**Comment by Lux-pogu** [comment]
> Make sure the correct folder is selected, and if it is then you may be missing files for your black ops 2
